#!/bin/bash
# ============================================================
#   MUSIC SYSTEM — PROJECT SETUP SCRIPT
# ============================================================

set -e

# ---------- ASK FOR MYSQL PASSWORD ----------
echo "=============================================="
echo "  MUSIC SYSTEM — SETUP STARTING"
echo "=============================================="
echo ""

read -sp "Enter MySQL root password: " PASSWORD
echo ""

# ---------- CONFIG ----------
DB_NAME="oho"
DB_USER="root"
SQL_DIR="./sql"
SRC_DIR="./src"
REQ_FILE="requirements.txt"
ENV_FILE="$SRC_DIR/.env"

# ---------- 1) Start MySQL ----------
echo "[1/4] Starting MySQL service..."
sudo service mysql start
echo "✓ MySQL started."
echo ""

# ---------- 2) Create Database ----------
echo "[2/4] Creating database ($DB_NAME)..."

mysql -u $DB_USER -p"$PASSWORD" -e "DROP DATABASE IF EXISTS $DB_NAME;"
mysql -u $DB_USER -p"$PASSWORD" -e "CREATE DATABASE $DB_NAME;"

echo "✓ Database created."
echo ""

# ---------- Confirming Env File ----------
if [ ! -f "$ENV_FILE" ]; then
    echo "[!] .env file not found in $SRC_DIR. Creating one..."

    # Escape password for .env safety
    ESCAPED_PASS=$(printf '%s\n' "$PASSWORD" | sed 's/"/\\"/g')

    cat <<EOL > "$ENV_FILE"
# Auto-generated by setup.sh
PASSWORD="$ESCAPED_PASS"
DB_HOST="localhost"
DB_USER="root"
DB_PORT="3306"
DB_NAME="oho"
EOL

    echo "✓ .env file created with default config."
    echo ""
else
    echo "[✓] .env file found in $SRC_DIR."
    echo ""
fi




# ---------- 3) Import SQL Files ----------
echo "[3/4] Importing SQL files..."

echo " → Importing backup.sql..."
mysql -u $DB_USER -p"$PASSWORD" "$DB_NAME" < "$SQL_DIR/backup.sql"

echo " → Importing functions.sql..."
mysql -u $DB_USER -p"$PASSWORD" "$DB_NAME" < "$SQL_DIR/functions.sql"

echo " → Importing procedures.sql..."
mysql -u $DB_USER -p"$PASSWORD" "$DB_NAME" < "$SQL_DIR/procedures.sql"

echo "✓ SQL import complete."
echo ""

# ---------- 4) Python Setup ----------
echo "[4/4] Setting up Python environment..."

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

source venv/bin/activate

pip install -r "$REQ_FILE"

echo "✓ Python ready."
echo ""

# ---------- Run the App ----------
echo "=============================================="
echo "     Setup complete. Launching app.py..."
echo "=============================================="
echo ""

python3 "$SRC_DIR/app.py"
